name: Pipeline de CI/CD - Meu Primeiro Robô

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rodar app
        run: node app.js

      - name: Sucesso
        run: echo "Pipeline executado com sucesso!"
